FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY docker-entrypoint-wrapper.sh /docker-entrypoint-wrapper.sh
RUN sed -i 's/\r$//' /docker-entrypoint-wrapper.sh && chmod +x /docker-entrypoint-wrapper.sh

EXPOSE 80 443

CMD ["/docker-entrypoint-wrapper.sh"]
